### PR TITLE
Adds flatten() to Option and Result

### PR DESCRIPTION
**Pull request by rrichardson**
This adds the flatten() method to Result and Option

### CODE REVIEW

**Comment by traverse1984** [comment]
I appreciate your interest in the project, but I'm afraid I can't merge this. The implementation is incredibly limited and makes changes which do not make sense. I don't think it's useful enough in the current form. In my view, flatten should also be recursive.

Additionally, your implementation changes `andThen` which is not acceptable. The core library needs to remain unchanged, and it shouldn't be necessary to modify an unrelated function to implement a new feature - especially when you could just duplicate the logic if it works similarly.

I think I see what you were going for with the `E1` though, but it doesn't actually do what you're thinking it does. This does not work:

```
const x: Result<Result<number, string>, number> = Ok(Ok(1));
const y = x.flatten(); // this context error
```

**Comment by rrichardson** [comment]
Actually.. the change to `andThen()` is unintentional. That is a remnant of prior experiments.  I would remove that.  
I don't think multiple error types is something that should be in scope for andThen and flatten. 

I adamantly disagree regarding `flatten` needing to be recursive.  There isn't a single implementation that I can think of that flattens recursively (neither Javascript, nor Rust, nor Haskell.)

**Comment by rrichardson** [comment]
FWIW, I've reverted the `andThen` type signature in my branch.

**Comment by traverse1984** [comment]
Okay, that makes more sense.

Javascripts built-in Array.flat allows you to specify the recursion depth. I probably should have said 'recursive capable'. However to keep with the Rust implementation it might be better to not include recursion depth as an option.

**Pull request closed without merging**
